version: '4'

services:
  db:
    container_name: budget-buddy
    image: postgres:latest
    environment:
      POSTGRES_USER: super_admin
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /data/budget-buddy
      POSTGRES_DB: budget-buddy
    volumes:
      - postgres-db:/data/budget-buddy
    ports:
      - "5432:5432"

volumes:
  postgres-db:
    driver: local
